spring:
  application:
    name: @project.artifactId@

  profiles:
    active: default

  datasource:
    url: jdbc:h2:mem:ja_startarer_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      platform: h2

logging:
  level:
    org.springframework.boot.autoconfigure: WARN

security:
    jwt:
      secret: "minhaSuperChaveSecreta123456"
      expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

project:
  name: @project.artifactId@
  version: @project.version@
  description: @project.description@